### PR TITLE
redesign page

### LINKED ISSUE #7: Improve design/interface.
The website looks kinda ugly rn, the design requires to be changed to look nice and believable, because this is a real product and people can actually win the prizes mentioned, no scam :)

### PR DESCRIPTION
**Pull request by thng17**
fixes #7 

I redesign the page like my wireframe.

notice: 
- I didn't change the button color thought it fits also in that page
- I add a file .gitignore to ignore the  ._( ... ). svg
- also add my own info-icon, bc the one I like in fontawome is only for pro user

you can check the redesign. If everything all right you can pull it. :)

### CODE REVIEW

**Comment by thng17** [comment]
Hey @KendallDoesCoding I'm not sure why I cannot add u as a reviewer. So u have any ideas?

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Looks really good to me, but can you please update the info text color to red or green, cause it is unreadable rn.

"Everything you click the button it will open a link, but the chance of winning any of the above listed prizes is as small as 0.0001%

If the bot on the surprise websites are open source, users can figure out issues and vulnerabilities with how it decides if you win a prize or if you don't, only the webpage where you have to tap the button to pick if you win a surprise or not is open source. The webpage run by a bot that decides if you win the prize or don't, which is hosted on another web page by KendallDoesCoding, is not an OPEN source.

If you win any prize, it will prompt you to fill basic contact details like email and the bot will spam me with emails and I will contact you within 24 hours."

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding I'm not sure why I cannot add you as a reviewer. Do you know why?

Yes, because you do not have collab access to this repo, I didn't want to put the CODEOWNERS file here to be automatically assigned, cause I anyway get an email.

**Comment by thng17** [comment]
@KendallDoesCoding: sure change the info text in red :)

**Review by KendallDoesCoding — APPROVED** [review]
Perfect! Thanks a ton. This is really amazing!!!

**Pull request merged**
